# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0002_auto_20180105_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poked_users',
            field=models.ManyToManyField(related_name='pokers', to='pokes.User'),
        ),
    ]
