# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0003_auto_20180105_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poke_count',
            field=models.IntegerField(default=0),
        ),
    ]
